name: 'NPM Custom Action'
description: 'Installing and Caching NPM packages'

inputs:
    path-of-folder: #id of input
        description: 'the path to cache'
        required: true

runs:
  using: "composite"
  steps: 
        # Caching the package-lock.json so that for subsequence workflows, we do not need to reinstall the packages. npm install will run faster
        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            path: ${{ inputs.path-of-folder }}
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}


        - name: Install Dependencies
          run: npm install
          shell: bash